groups:
- name: ssl_cert_expiry_alert
  rules:
  - alert: SSLCertificateExpiringSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 15
    for: 5m
    labels:
      severity: warning
    annotations:
      sumgary: "SSL certificate is expiring soon ({{ $labels.probe_target }})"
      description: "SSL certificate for {{ $labels.probe_target }} expires in less than 15 days."

